version: "3.8"

services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: ./
      args:
        PHP_VERSION: ${PHP_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        ENABLE_LEAD_AUTOGENERATE: ${ENABLE_LEAD_AUTOGENERATE}
    working_dir: /var/www
    volumes:
      - ~/.ssh:/var/www/.ssh
      - project:/var/www
    ports:
      - "${INTERFACE}:${PHP_FPM_PORT}:9000"
    environment:
      XDEBUG_CONFIG: "client_host=${XDEBUG_HOST} start_with_request=${XDEBUG_START_WITH_REQUEST} mode=${XDEBUG_MODE}"
volumes:
  project:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_PATH}
